FROM elixir:1.15.4-slim

RUN apt-get update \
    && apt-get install -y apt-utils \
    && apt-get install -y build-essential \
    && apt-get install -y inotify-tools

RUN mix local.hex --force, mix.local.rebar --force

WORKDIR /app

ENTRYPOINT [ "mix", "phx.server" ]
