version: '3'

services:
  dev-database:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=volko_dev
  # test-database:
  #   image: postgres
  #   ports:
  #     - '5432:5433'
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=volko_test
  #   volumes:
  #     - dev-volume:/var/lib/postgresql/data

volumes:
  dev-volume: